name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Saving cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          yarn install

      - name: Check linting
        run: yarn lint

      - name: Check TS
        run: yarn check-ts

      # - name: Check tests
      #   run: |
      #     yarn test
